version: '2'
services:
  emcc:
    container_name: "docker_emscripten"
    build:
      context: "./dockerfiles"
      dockerfile: "Dockerfile_use_dockerhub"
#      args:
#        APT_GET_MIRROR: "http://ftp.jaist.ac.jp/pub/Linux/ubuntu/"
#        EMSCRIPTEN_VERSION: "1.37.33"
    ports:
      - "6080:6080"
    volumes:
      - ./src:/opt/src
    privileged: true
