version: '2'
services:
  emcc:
    container_name: "docker_emscripten"
    build:
      context: "./dockerfiles"
      dockerfile: "Dockerfile_use_emsdk"
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    privileged: true
